In [25]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [26]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.cross_validation import train_test_split

In [27]:
from sklearn.datasets import load_iris

In [28]:
iris = load_iris()

In [29]:
target = iris.target
features = iris.data

In [30]:
x_train, x_test, Y_train, Y_test = train_test_split(features, target, test_size=.20)

In [31]:
clf = DecisionTreeClassifier()

In [32]:
clf.fit(x_train, Y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=None, splitter='best')

In [33]:
clf.feature_importances_

array([ 0.        ,  0.01875391,  0.55934629,  0.42189981])

In [34]:
clf.classes_

array([0, 1, 2])

In [35]:
clf.predict(x_test)

array([1, 0, 2, 2, 1, 2, 2, 2, 1, 0, 0, 0, 1, 0, 1, 0, 0, 2, 0, 2, 2, 1, 1,
       2, 0, 2, 1, 1, 1, 2])

In [36]:
clf.predict_proba(x_test)

array([[ 0.,  1.,  0.],
       [ 1.,  0.,  0.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       [ 0.,  1.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 0.,  0.,  1.],
       [ 1.,  0.,  0.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.],
       [ 1.,  0.,  0.],
       [ 0.,  0.,  1.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [37]:
from sklearn import tree

In [38]:
tree.export_graphviz(clf, out_file='tree.dot')

In [15]:
from sklearn.externals.six import StringIO
import pydotplus

In [16]:
dot_data = StringIO()
tree.export_graphviz(clf, out_file = dot_data,
                    feature_names = iris.feature_names,
                    class_names = iris.target_names,
                    filled = True,
                    rounded = True,
                    impurity = False)
graph = pydotplus.graph_from_dot_data(dot_data.getvalue())
graph.write_pdf("iris.pdf")

True

In [39]:
from IPython.display import IFrame
IFrame("iris.pdf", width=700, height=500 )

In [41]:
x_test[0]

array([ 5.8,  2.6,  4. ,  1.2])

In [42]:
clf.predict(x_test[0])

G:\Python\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


array([1])

In [43]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], 
      dtype='<U10')

In [44]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']